/* Original classroom boss catalogue. See docs/classroom-battle.md. */
(function(root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else root.ClassroomBosses = factory(); })(typeof globalThis !== "undefined" ? globalThis : this, function() { return [
  {
    "id": "mossback",
    "name": "Mossback Guardian",
    "subject": "a stout moss-and-stone tortoise golem, leafy shell, amber eyes, sturdy four feet, small flowers",
    "attack": "Pebble Pop",
    "ultimate": "Forest Rumble",
    "playstyle": "armored",
    "description": "High defence; slow, steady hits.",
    "hpMultiplier": 1.2,
    "attackMultiplier": 0.85,
    "ultimateCharge": 3,
    "defence": 0.2,
    "color": "#6fbf73",
    "image": "assets/classroom-bosses/mossback.png",
    "attackName": "Pebble Pop",
    "ultimateName": "Forest Rumble",
    "chargeMax": 3
  },
  {
    "id": "cinderpuff",
    "name": "Cinderpuff Dragon",
    "subject": "a round coral-orange baby dragon with tiny teal wings, curling tail and glowing ember belly",
    "attack": "Ember Puff",
    "ultimate": "Firework Breath",
    "playstyle": "burn",
    "description": "Low armour; powerful single-target embers.",
    "hpMultiplier": 0.95,
    "attackMultiplier": 1.2,
    "ultimateCharge": 4,
    "defence": 0,
    "color": "#ff8758",
    "image": "assets/classroom-bosses/cinderpuff.png",
    "attackName": "Ember Puff",
    "ultimateName": "Firework Breath",
    "chargeMax": 4
  },
  {
    "id": "bubblebeard",
    "name": "Captain Bubblebeard",
    "subject": "a turquoise octopus sea captain with a bubble beard, golden shell hat and eight fully visible tentacles",
    "attack": "Bubble Bolt",
    "ultimate": "Tidal Splash",
    "playstyle": "splash",
    "description": "Splash attacks spread damage across the team.",
    "hpMultiplier": 1.05,
    "attackMultiplier": 0.85,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#42cedd",
    "image": "assets/classroom-bosses/bubblebeard.png",
    "attackName": "Bubble Bolt",
    "ultimateName": "Tidal Splash",
    "chargeMax": 3
  },
  {
    "id": "crystalhoof",
    "name": "Crystalhoof Stag",
    "subject": "a majestic chunky violet crystal deer with translucent branching antlers, four hooves and a friendly glowing face",
    "attack": "Prism Shard",
    "ultimate": "Rainbow Burst",
    "playstyle": "reflect",
    "description": "Crystal armour rewards consistent teamwork.",
    "hpMultiplier": 1.05,
    "attackMultiplier": 1.05,
    "ultimateCharge": 4,
    "defence": 0.15,
    "color": "#be96ff",
    "image": "assets/classroom-bosses/crystalhoof.png",
    "attackName": "Prism Shard",
    "ultimateName": "Rainbow Burst",
    "chargeMax": 4
  },
  {
    "id": "geargrin",
    "name": "Geargrin Automaton",
    "subject": "a cheerful brass clockwork robot with oversized gear shoulders, spring legs, mitten hands and a windup key",
    "attack": "Cog Toss",
    "ultimate": "Clockwork Cascade",
    "playstyle": "charge",
    "description": "Quick ultimate charge; light normal hits.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.8,
    "ultimateCharge": 2,
    "defence": 0.1,
    "color": "#e7ba61",
    "image": "assets/classroom-bosses/geargrin.png",
    "attackName": "Cog Toss",
    "ultimateName": "Clockwork Cascade",
    "chargeMax": 2
  },
  {
    "id": "stormwhisker",
    "name": "Stormwhisker Lynx",
    "subject": "a fluffy electric-blue lynx with cloud paws, lightning-shaped whiskers and a curled glowing tail",
    "attack": "Spark Pounce",
    "ultimate": "Thundercloud Parade",
    "playstyle": "swift",
    "description": "Fast double-strike normal attacks.",
    "hpMultiplier": 0.9,
    "attackMultiplier": 0.85,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#74b7ff",
    "image": "assets/classroom-bosses/stormwhisker.png",
    "attackName": "Spark Pounce",
    "ultimateName": "Thundercloud Parade",
    "chargeMax": 3
  },
  {
    "id": "jellycrown",
    "name": "Jellycrown Monarch",
    "subject": "a wobbly lime-green jelly king with floating golden crown, tiny arms and rounded jelly feet",
    "attack": "Jelly Glob",
    "ultimate": "Royal Wobble",
    "playstyle": "regenerate",
    "description": "Restores a little health after normal attacks.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 0.8,
    "ultimateCharge": 4,
    "defence": 0,
    "color": "#a5dd60",
    "image": "assets/classroom-bosses/jellycrown.png",
    "attackName": "Jelly Glob",
    "ultimateName": "Royal Wobble",
    "chargeMax": 4
  },
  {
    "id": "sandspire",
    "name": "Sandspire Sphinx",
    "subject": "a friendly sandstone sphinx with feline body, turquoise geometric wings and a rounded sun headdress",
    "attack": "Sand Marble",
    "ultimate": "Desert Swirl",
    "playstyle": "armored",
    "description": "Tough armour with a slower ultimate.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 1,
    "ultimateCharge": 5,
    "defence": 0.25,
    "color": "#e6bf7a",
    "image": "assets/classroom-bosses/sandspire.png",
    "attackName": "Sand Marble",
    "ultimateName": "Desert Swirl",
    "chargeMax": 5
  },
  {
    "id": "snowmallow",
    "name": "Snowmallow Yeti",
    "subject": "a cuddly white yeti with ice-blue mittens, purple nose, fluffy feet and a scarf made from snowflakes",
    "attack": "Snowball Toss",
    "ultimate": "Snowday Avalanche",
    "playstyle": "splash",
    "description": "Gentle team splash; stronger all-team ultimate.",
    "hpMultiplier": 1.2,
    "attackMultiplier": 0.8,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#b5e6ff",
    "image": "assets/classroom-bosses/snowmallow.png",
    "attackName": "Snowball Toss",
    "ultimateName": "Snowday Avalanche",
    "chargeMax": 3
  },
  {
    "id": "sunpetal",
    "name": "Sunpetal Treant",
    "subject": "a walking sunflower tree giant with wooden legs, leafy arms, sunny petal mane and seed-button eyes",
    "attack": "Seed Sling",
    "ultimate": "Petal Cyclone",
    "playstyle": "regenerate",
    "description": "Restores a little health; rewards burst attacks.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 3,
    "defence": 0.1,
    "color": "#f7ce55",
    "image": "assets/classroom-bosses/sunpetal.png",
    "attackName": "Seed Sling",
    "ultimateName": "Petal Cyclone",
    "chargeMax": 3
  },
  {
    "id": "moonmoth",
    "name": "Moonmoth Oracle",
    "subject": "a lavender luna moth wizard with huge crescent-patterned wings, fuzzy antennae, tiny feet and a star wand",
    "attack": "Moonbeam",
    "ultimate": "Starlight Shower",
    "playstyle": "pierce",
    "description": "Magic attacks partially bypass defence.",
    "hpMultiplier": 0.9,
    "attackMultiplier": 1.1,
    "ultimateCharge": 4,
    "defence": 0,
    "color": "#baa3f0",
    "image": "assets/classroom-bosses/moonmoth.png",
    "attackName": "Moonbeam",
    "ultimateName": "Starlight Shower",
    "chargeMax": 4
  },
  {
    "id": "rockhopper",
    "name": "Rockhopper Rex",
    "subject": "a friendly squat teal dinosaur with pebble armour plates, big hind feet, little forearms and rounded tail",
    "attack": "Boulder Bounce",
    "ultimate": "Meteor Hop",
    "playstyle": "heavy",
    "description": "Strong focused strikes with slow ultimate.",
    "hpMultiplier": 1.2,
    "attackMultiplier": 1.3,
    "ultimateCharge": 5,
    "defence": 0.1,
    "color": "#69b6ab",
    "image": "assets/classroom-bosses/rockhopper.png",
    "attackName": "Boulder Bounce",
    "ultimateName": "Meteor Hop",
    "chargeMax": 5
  },
  {
    "id": "inktip",
    "name": "Inktip Scholar",
    "subject": "a small indigo squid scholar with a floppy academic cap, glowing ink quill and eight curled tentacles",
    "attack": "Ink Drop",
    "ultimate": "Inkstorm Scribble",
    "playstyle": "weaken",
    "description": "Ink softens the next hero attack.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#8b8fd2",
    "image": "assets/classroom-bosses/inktip.png",
    "attackName": "Ink Drop",
    "ultimateName": "Inkstorm Scribble",
    "chargeMax": 3
  },
  {
    "id": "thistletuft",
    "name": "Thistletuft Hedgehog",
    "subject": "a giant round magenta hedgehog with soft leaf quills, mushroom shield and four stubby paws",
    "attack": "Thistle Flick",
    "ultimate": "Bramble Ballet",
    "playstyle": "reflect",
    "description": "Quills gently counter successful attacks.",
    "hpMultiplier": 1.05,
    "attackMultiplier": 0.8,
    "ultimateCharge": 4,
    "defence": 0.1,
    "color": "#ce82a7",
    "image": "assets/classroom-bosses/thistletuft.png",
    "attackName": "Thistle Flick",
    "ultimateName": "Bramble Ballet",
    "chargeMax": 4
  },
  {
    "id": "cometfin",
    "name": "Cometfin Ray",
    "subject": "a floating midnight-blue manta ray with star speckles, glowing comet tail, little fins and bright eyes",
    "attack": "Star Dart",
    "ultimate": "Comet Shower",
    "playstyle": "swift",
    "description": "Two quick star darts challenge healers.",
    "hpMultiplier": 0.9,
    "attackMultiplier": 0.95,
    "ultimateCharge": 3,
    "defence": 0,
    "color": "#777fed",
    "image": "assets/classroom-bosses/cometfin.png",
    "attackName": "Star Dart",
    "ultimateName": "Comet Shower",
    "chargeMax": 3
  },
  {
    "id": "honeyhelm",
    "name": "Honeyhelm Beetle",
    "subject": "a golden honey beetle knight with amber shell, tiny blue cape, six rounded legs and acorn helmet",
    "attack": "Honey Orb",
    "ultimate": "Golden Drizzle",
    "playstyle": "guard",
    "description": "Periodically guards against the next hit.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 4,
    "defence": 0.15,
    "color": "#eda846",
    "image": "assets/classroom-bosses/honeyhelm.png",
    "attackName": "Honey Orb",
    "ultimateName": "Golden Drizzle",
    "chargeMax": 4
  },
  {
    "id": "tideclaw",
    "name": "Tideclaw Crab",
    "subject": "a large cheerful coral-pink hermit crab with a seashell castle, flag, six visible legs and two rounded claws",
    "attack": "Shell Skipper",
    "ultimate": "Whirlpool Waltz",
    "playstyle": "armored",
    "description": "Shell reduces damage; ultimate is patient.",
    "hpMultiplier": 1.25,
    "attackMultiplier": 0.95,
    "ultimateCharge": 5,
    "defence": 0.2,
    "color": "#ffaaa1",
    "image": "assets/classroom-bosses/tideclaw.png",
    "attackName": "Shell Skipper",
    "ultimateName": "Whirlpool Waltz",
    "chargeMax": 5
  },
  {
    "id": "echobat",
    "name": "Echochime Bat",
    "subject": "a friendly mint-and-purple bat with bell-shaped ears, broad musical-patterned wings and tiny feet",
    "attack": "Chime Pulse",
    "ultimate": "Echo Orchestra",
    "playstyle": "pierce",
    "description": "Sound waves partly bypass armour.",
    "hpMultiplier": 0.95,
    "attackMultiplier": 1,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#9ac9bf",
    "image": "assets/classroom-bosses/echobat.png",
    "attackName": "Chime Pulse",
    "ultimateName": "Echo Orchestra",
    "chargeMax": 3
  },
  {
    "id": "pumpkinpip",
    "name": "Pumpkinpip Sprite",
    "subject": "a whimsical orange pumpkin sprite with vine arms, root boots, leafy wizard hat and a smiling carved face",
    "attack": "Pip Pop",
    "ultimate": "Harvest Hooray",
    "playstyle": "charge",
    "description": "Quick ultimate charge keeps turns lively.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 2,
    "defence": 0.05,
    "color": "#f4aa62",
    "image": "assets/classroom-bosses/pumpkinpip.png",
    "attackName": "Pip Pop",
    "ultimateName": "Harvest Hooray",
    "chargeMax": 2
  },
  {
    "id": "auroruff",
    "name": "Auroruff Wolf",
    "subject": "a fluffy white arctic wolf with rainbow aurora mane, four paws, silver ear tips and a curling celestial tail",
    "attack": "Aurora Bolt",
    "ultimate": "Northern Lights",
    "playstyle": "balanced",
    "description": "Balanced attacks and an all-team light wave.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 1,
    "ultimateCharge": 4,
    "defence": 0.1,
    "color": "#8fd9d5",
    "image": "assets/classroom-bosses/auroruff.png",
    "attackName": "Aurora Bolt",
    "ultimateName": "Northern Lights",
    "chargeMax": 4
  }
]; });