/* 100 playable bosses plus 20 historical classroom bosses. Art provenance: assets/battle-pixel/bosses/provenance.json. */
(function(root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else root.ClassroomBosses = factory(); })(typeof globalThis !== "undefined" ? globalThis : this, function() { return [
  {
    "id": "mossback",
    "name": "Mossback Guardian",
    "subject": "a stout moss-and-stone tortoise golem, leafy shell, amber eyes, sturdy four feet, small flowers",
    "attack": "Pebble Pop",
    "ultimate": "Forest Rumble",
    "playstyle": "armored",
    "description": "High defence; slow, steady hits.",
    "hpMultiplier": 1.2,
    "attackMultiplier": 0.85,
    "ultimateCharge": 3,
    "defence": 0.2,
    "color": "#6fbf73",
    "image": "assets/classroom-bosses/mossback.png",
    "attackName": "Pebble Pop",
    "ultimateName": "Forest Rumble",
    "chargeMax": 3
  },
  {
    "id": "cinderpuff",
    "name": "Cinderpuff Dragon",
    "subject": "a round coral-orange baby dragon with tiny teal wings, curling tail and glowing ember belly",
    "attack": "Ember Puff",
    "ultimate": "Firework Breath",
    "playstyle": "burn",
    "description": "Low armour; powerful single-target embers.",
    "hpMultiplier": 0.95,
    "attackMultiplier": 1.2,
    "ultimateCharge": 4,
    "defence": 0,
    "color": "#ff8758",
    "image": "assets/classroom-bosses/cinderpuff.png",
    "attackName": "Ember Puff",
    "ultimateName": "Firework Breath",
    "chargeMax": 4
  },
  {
    "id": "bubblebeard",
    "name": "Captain Bubblebeard",
    "subject": "a turquoise octopus sea captain with a bubble beard, golden shell hat and eight fully visible tentacles",
    "attack": "Bubble Bolt",
    "ultimate": "Tidal Splash",
    "playstyle": "splash",
    "description": "Splash attacks spread damage across the team.",
    "hpMultiplier": 1.05,
    "attackMultiplier": 0.85,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#42cedd",
    "image": "assets/classroom-bosses/bubblebeard.png",
    "attackName": "Bubble Bolt",
    "ultimateName": "Tidal Splash",
    "chargeMax": 3
  },
  {
    "id": "crystalhoof",
    "name": "Crystalhoof Stag",
    "subject": "a majestic chunky violet crystal deer with translucent branching antlers, four hooves and a friendly glowing face",
    "attack": "Prism Shard",
    "ultimate": "Rainbow Burst",
    "playstyle": "reflect",
    "description": "Crystal armour rewards consistent teamwork.",
    "hpMultiplier": 1.05,
    "attackMultiplier": 1.05,
    "ultimateCharge": 4,
    "defence": 0.15,
    "color": "#be96ff",
    "image": "assets/classroom-bosses/crystalhoof.png",
    "attackName": "Prism Shard",
    "ultimateName": "Rainbow Burst",
    "chargeMax": 4
  },
  {
    "id": "geargrin",
    "name": "Geargrin Automaton",
    "subject": "a cheerful brass clockwork robot with oversized gear shoulders, spring legs, mitten hands and a windup key",
    "attack": "Cog Toss",
    "ultimate": "Clockwork Cascade",
    "playstyle": "charge",
    "description": "Quick ultimate charge; light normal hits.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.8,
    "ultimateCharge": 2,
    "defence": 0.1,
    "color": "#e7ba61",
    "image": "assets/classroom-bosses/geargrin.png",
    "attackName": "Cog Toss",
    "ultimateName": "Clockwork Cascade",
    "chargeMax": 2
  },
  {
    "id": "stormwhisker",
    "name": "Stormwhisker Lynx",
    "subject": "a fluffy electric-blue lynx with cloud paws, lightning-shaped whiskers and a curled glowing tail",
    "attack": "Spark Pounce",
    "ultimate": "Thundercloud Parade",
    "playstyle": "swift",
    "description": "Fast double-strike normal attacks.",
    "hpMultiplier": 0.9,
    "attackMultiplier": 0.85,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#74b7ff",
    "image": "assets/classroom-bosses/stormwhisker.png",
    "attackName": "Spark Pounce",
    "ultimateName": "Thundercloud Parade",
    "chargeMax": 3
  },
  {
    "id": "jellycrown",
    "name": "Jellycrown Monarch",
    "subject": "a wobbly lime-green jelly king with floating golden crown, tiny arms and rounded jelly feet",
    "attack": "Jelly Glob",
    "ultimate": "Royal Wobble",
    "playstyle": "regenerate",
    "description": "Restores a little health after normal attacks.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 0.8,
    "ultimateCharge": 4,
    "defence": 0,
    "color": "#a5dd60",
    "image": "assets/classroom-bosses/jellycrown.png",
    "attackName": "Jelly Glob",
    "ultimateName": "Royal Wobble",
    "chargeMax": 4
  },
  {
    "id": "sandspire",
    "name": "Sandspire Sphinx",
    "subject": "a friendly sandstone sphinx with feline body, turquoise geometric wings and a rounded sun headdress",
    "attack": "Sand Marble",
    "ultimate": "Desert Swirl",
    "playstyle": "armored",
    "description": "Tough armour with a slower ultimate.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 1,
    "ultimateCharge": 5,
    "defence": 0.25,
    "color": "#e6bf7a",
    "image": "assets/classroom-bosses/sandspire.png",
    "attackName": "Sand Marble",
    "ultimateName": "Desert Swirl",
    "chargeMax": 5
  },
  {
    "id": "snowmallow",
    "name": "Snowmallow Yeti",
    "subject": "a cuddly white yeti with ice-blue mittens, purple nose, fluffy feet and a scarf made from snowflakes",
    "attack": "Snowball Toss",
    "ultimate": "Snowday Avalanche",
    "playstyle": "splash",
    "description": "Gentle team splash; stronger all-team ultimate.",
    "hpMultiplier": 1.2,
    "attackMultiplier": 0.8,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#b5e6ff",
    "image": "assets/classroom-bosses/snowmallow.png",
    "attackName": "Snowball Toss",
    "ultimateName": "Snowday Avalanche",
    "chargeMax": 3
  },
  {
    "id": "sunpetal",
    "name": "Sunpetal Treant",
    "subject": "a walking sunflower tree giant with wooden legs, leafy arms, sunny petal mane and seed-button eyes",
    "attack": "Seed Sling",
    "ultimate": "Petal Cyclone",
    "playstyle": "regenerate",
    "description": "Restores a little health; rewards burst attacks.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 3,
    "defence": 0.1,
    "color": "#f7ce55",
    "image": "assets/classroom-bosses/sunpetal.png",
    "attackName": "Seed Sling",
    "ultimateName": "Petal Cyclone",
    "chargeMax": 3
  },
  {
    "id": "moonmoth",
    "name": "Moonmoth Oracle",
    "subject": "a lavender luna moth wizard with huge crescent-patterned wings, fuzzy antennae, tiny feet and a star wand",
    "attack": "Moonbeam",
    "ultimate": "Starlight Shower",
    "playstyle": "pierce",
    "description": "Magic attacks partially bypass defence.",
    "hpMultiplier": 0.9,
    "attackMultiplier": 1.1,
    "ultimateCharge": 4,
    "defence": 0,
    "color": "#baa3f0",
    "image": "assets/classroom-bosses/moonmoth.png",
    "attackName": "Moonbeam",
    "ultimateName": "Starlight Shower",
    "chargeMax": 4
  },
  {
    "id": "rockhopper",
    "name": "Rockhopper Rex",
    "subject": "a friendly squat teal dinosaur with pebble armour plates, big hind feet, little forearms and rounded tail",
    "attack": "Boulder Bounce",
    "ultimate": "Meteor Hop",
    "playstyle": "heavy",
    "description": "Strong focused strikes with slow ultimate.",
    "hpMultiplier": 1.2,
    "attackMultiplier": 1.3,
    "ultimateCharge": 5,
    "defence": 0.1,
    "color": "#69b6ab",
    "image": "assets/classroom-bosses/rockhopper.png",
    "attackName": "Boulder Bounce",
    "ultimateName": "Meteor Hop",
    "chargeMax": 5
  },
  {
    "id": "inktip",
    "name": "Inktip Scholar",
    "subject": "a small indigo squid scholar with a floppy academic cap, glowing ink quill and eight curled tentacles",
    "attack": "Ink Drop",
    "ultimate": "Inkstorm Scribble",
    "playstyle": "weaken",
    "description": "Ink softens the next hero attack.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#8b8fd2",
    "image": "assets/classroom-bosses/inktip.png",
    "attackName": "Ink Drop",
    "ultimateName": "Inkstorm Scribble",
    "chargeMax": 3
  },
  {
    "id": "thistletuft",
    "name": "Thistletuft Hedgehog",
    "subject": "a giant round magenta hedgehog with soft leaf quills, mushroom shield and four stubby paws",
    "attack": "Thistle Flick",
    "ultimate": "Bramble Ballet",
    "playstyle": "reflect",
    "description": "Quills gently counter successful attacks.",
    "hpMultiplier": 1.05,
    "attackMultiplier": 0.8,
    "ultimateCharge": 4,
    "defence": 0.1,
    "color": "#ce82a7",
    "image": "assets/classroom-bosses/thistletuft.png",
    "attackName": "Thistle Flick",
    "ultimateName": "Bramble Ballet",
    "chargeMax": 4
  },
  {
    "id": "cometfin",
    "name": "Cometfin Ray",
    "subject": "a floating midnight-blue manta ray with star speckles, glowing comet tail, little fins and bright eyes",
    "attack": "Star Dart",
    "ultimate": "Comet Shower",
    "playstyle": "swift",
    "description": "Two quick star darts challenge healers.",
    "hpMultiplier": 0.9,
    "attackMultiplier": 0.95,
    "ultimateCharge": 3,
    "defence": 0,
    "color": "#777fed",
    "image": "assets/classroom-bosses/cometfin.png",
    "attackName": "Star Dart",
    "ultimateName": "Comet Shower",
    "chargeMax": 3
  },
  {
    "id": "honeyhelm",
    "name": "Honeyhelm Beetle",
    "subject": "a golden honey beetle knight with amber shell, tiny blue cape, six rounded legs and acorn helmet",
    "attack": "Honey Orb",
    "ultimate": "Golden Drizzle",
    "playstyle": "guard",
    "description": "Periodically guards against the next hit.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 4,
    "defence": 0.15,
    "color": "#eda846",
    "image": "assets/classroom-bosses/honeyhelm.png",
    "attackName": "Honey Orb",
    "ultimateName": "Golden Drizzle",
    "chargeMax": 4
  },
  {
    "id": "tideclaw",
    "name": "Tideclaw Crab",
    "subject": "a large cheerful coral-pink hermit crab with a seashell castle, flag, six visible legs and two rounded claws",
    "attack": "Shell Skipper",
    "ultimate": "Whirlpool Waltz",
    "playstyle": "armored",
    "description": "Shell reduces damage; ultimate is patient.",
    "hpMultiplier": 1.25,
    "attackMultiplier": 0.95,
    "ultimateCharge": 5,
    "defence": 0.2,
    "color": "#ffaaa1",
    "image": "assets/classroom-bosses/tideclaw.png",
    "attackName": "Shell Skipper",
    "ultimateName": "Whirlpool Waltz",
    "chargeMax": 5
  },
  {
    "id": "echobat",
    "name": "Echochime Bat",
    "subject": "a friendly mint-and-purple bat with bell-shaped ears, broad musical-patterned wings and tiny feet",
    "attack": "Chime Pulse",
    "ultimate": "Echo Orchestra",
    "playstyle": "pierce",
    "description": "Sound waves partly bypass armour.",
    "hpMultiplier": 0.95,
    "attackMultiplier": 1,
    "ultimateCharge": 3,
    "defence": 0.05,
    "color": "#9ac9bf",
    "image": "assets/classroom-bosses/echobat.png",
    "attackName": "Chime Pulse",
    "ultimateName": "Echo Orchestra",
    "chargeMax": 3
  },
  {
    "id": "pumpkinpip",
    "name": "Pumpkinpip Sprite",
    "subject": "a whimsical orange pumpkin sprite with vine arms, root boots, leafy wizard hat and a smiling carved face",
    "attack": "Pip Pop",
    "ultimate": "Harvest Hooray",
    "playstyle": "charge",
    "description": "Quick ultimate charge keeps turns lively.",
    "hpMultiplier": 1,
    "attackMultiplier": 0.9,
    "ultimateCharge": 2,
    "defence": 0.05,
    "color": "#f4aa62",
    "image": "assets/classroom-bosses/pumpkinpip.png",
    "attackName": "Pip Pop",
    "ultimateName": "Harvest Hooray",
    "chargeMax": 2
  },
  {
    "id": "auroruff",
    "name": "Auroruff Wolf",
    "subject": "a fluffy white arctic wolf with rainbow aurora mane, four paws, silver ear tips and a curling celestial tail",
    "attack": "Aurora Bolt",
    "ultimate": "Northern Lights",
    "playstyle": "balanced",
    "description": "Balanced attacks and an all-team light wave.",
    "hpMultiplier": 1.1,
    "attackMultiplier": 1,
    "ultimateCharge": 4,
    "defence": 0.1,
    "color": "#8fd9d5",
    "image": "assets/classroom-bosses/auroruff.png",
    "attackName": "Aurora Bolt",
    "ultimateName": "Northern Lights",
    "chargeMax": 4
  }
].map(b => Object.assign({},b,{legacy:true})).concat([
  {id:'goblin',name:'Mossfang Goblin',description:'A weak forest raider. A friendly first encounter for a new party.',
    tier:'Skirmish',playstyle:'balanced',hpMultiplier:.45,attackMultiplier:.45,defence:0,chargeMax:3,rewardXp:45,
    attackName:'Rusty Dagger',ultimateName:'Goblin Rush',color:'#85bc78',image:'assets/battle-pixel/goblin.png',legacy:false},
  {id:'slime',name:'Sapphire Slime',description:'A gentle starter enemy that slowly reforms after each attack.',
    tier:'Skirmish',playstyle:'regenerate',hpMultiplier:.6,attackMultiplier:.5,defence:.03,chargeMax:4,rewardXp:55,
    attackName:'Jelly Bump',ultimateName:'Slime Shower',color:'#67cce1',image:'assets/battle-pixel/slime.png',legacy:false},
  {id:'goblin-shaman',name:'Bramblehex Shaman',description:'This goblin spellcaster curses the next hero attack. Cleanse or shield your allies.',
    tier:'Elite',playstyle:'weaken',hpMultiplier:.85,attackMultiplier:.85,defence:.06,chargeMax:3,rewardXp:80,
    attackName:'Hex Spark',ultimateName:'Bramble Curse',color:'#b9a0db',image:'assets/battle-pixel/goblin-shaman.png',legacy:false},
  {id:'golem',name:'Obsidian Sentinel',description:'An armoured elite with crushing blows. Armour-piercing skills help break its shell.',
    tier:'Elite',playstyle:'guard',hpMultiplier:1.35,attackMultiplier:1.05,defence:.28,chargeMax:4,rewardXp:115,
    attackName:'Stone Hammer',ultimateName:'Mountain Collapse',color:'#bf9c71',image:'assets/battle-pixel/golem.png',legacy:false},
  {id:'dragon',name:'Cinderwing Ancient',description:'A mighty dragon whose flame breath hits the whole party. Bring healing and protective wards.',
    tier:'Boss',playstyle:'splash',hpMultiplier:2.15,attackMultiplier:1.45,defence:.16,chargeMax:3,rewardXp:180,
    attackName:'Flame Breath',ultimateName:'Crimson Cataclysm',color:'#f3a36f',image:'assets/battle-pixel/dragon.png',legacy:false},
  {id:'lich',name:'The Astral Lich',description:'An endgame sorcerer with armour-piercing magic and a devastating cosmic ultimate.',
    tier:'Mythic boss',playstyle:'pierce',hpMultiplier:2.75,attackMultiplier:1.65,defence:.22,chargeMax:3,rewardXp:230,
    attackName:'Soulfire Bolt',ultimateName:'Eclipse of Eternity',color:'#b995f1',image:'assets/battle-pixel/lich.png',legacy:false}
]).concat([
    ["brambleboar","Bramblehide Boar","a russet wild boar with mossy tusks, leafy bristle mane and four sturdy hooves","Bramble Tusk","Thicket Stampede","balanced","common","#9bad68"],
    ["acornknight","Acorncap Knight","a small oak-armored squirrel knight carrying an acorn shield and branch lance","Acorn Jab","Oakguard Charge","guard","uncommon","#bd8c53"],
    ["lanternowl","Lanternwing Owl","a teal owl with glowing amber lantern feathers and spread rounded wings","Lantern Flash","Midnight Beacon","weaken","rare","#57b9b8"],
    ["thornstag","Thorncrown Stag","an emerald stag with twisting thorn antlers and a violet flower chest crest","Thorn Volley","Briar Coronation","reflect","epic","#72b66c"],
    ["rootmaw","Rootmaw Colossus","a massive dark oak root giant with orange hollow eyes and thick branch arms","Root Hammer","Forest Uprising","splash","legendary","#b18b5c"],
    ["sapserpent","Sapscale Serpent","a golden tree-sap serpent with leaf fins and a spiraling emerald tail","Sap Spit","Verdant Renewal","regenerate","uncommon","#dbb452"],
    ["fernmantis","Fernblade Mantis","a bright green mantis with fern frond blade forearms and six thin legs","Frond Slash","Leafblade Dance","swift","rare","#83bf61"],
    ["puffspore","Puffspore Monarch","a squat violet mushroom giant with golden spotted cap and stubby root feet","Spore Puff","Fungal Jubilee","weaken","common","#b58fce"],
    ["barkwarden","Barkshield Warden","a stout chestnut bark golem with a round wood shield and glowing blue rune eye","Bark Bash","Ancient Bulwark","guard","epic","#ba905e"],
    ["blossomwyvern","Blossomwing Wyvern","a pink and ivory flower wyvern with petal wings, tiny horns and curling green tail","Petal Breath","Bloom of Ages","pierce","mythical","#ee9ac1"],
    ["mudmaw","Mudmaw Crocodile","an olive crocodile with muddy stone scales, broad jaws and four short legs","Mud Snap","Marshquake","balanced","common","#8a9b62"],
    ["bogwitch","Boglight Witch","a purple frog witch wearing a reed hat and holding a blue will-o-wisp staff","Bog Hex","Marshlight Coven","weaken","rare","#9d86cb"],
    ["reedstalker","Reedcloak Stalker","a long-legged heron rogue with green reed cloak and curved wooden beak dagger","Reed Strike","Silent Marsh","swift","uncommon","#77b69b"],
    ["miretoad","Mirebell Toad","a large orange toad with green lily-pad collar and bell-shaped cheek pouches","Bell Croak","Echoing Mire","splash","epic","#e3a35d"],
    ["mosslamprey","Mossjaw Lamprey","a curling turquoise lamprey with moss frills and a ring of small ivory teeth","Moss Bite","Leeching Tide","regenerate","uncommon","#6dafae"],
    ["willowwisp","Willowveil Wisp","a floating pale-blue spirit in a willow-leaf hood with two glowing eyes and curled ghost tail","Willow Spark","Wispfall","pierce","rare","#9bdbde"],
    ["lilyhydra","Lilypad Hydra","a three-headed jade swamp hydra with lotus crests and a stout four-legged body","Triple Splash","Lotus Flood","splash","legendary","#72bfa0"],
    ["rotcap","Rotcap Alchemist","a russet mushroom alchemist with a black spotted cap, blue potion and woven satchel","Bubbling Flask","Sporebrew Surge","charge","common","#bb8370"],
    ["sludgeknight","Sludgeplate Knight","a stocky green slime knight inside dented bronze armor with a dripping shield","Sludge Bash","Mirewall","guard","epic","#93b15c"],
    ["fenbasilisk","Fenfire Basilisk","a black and emerald six-legged basilisk with amber crown spikes and luminous eyes","Fenfire Gaze","Swampstar Eclipse","reflect","mythical","#8bc35c"],
    ["cragram","Craghoof Ram","a gray mountain ram with oversized spiral stone horns and a red braided mane","Horn Bump","Crag Charge","balanced","common","#b1a09a"],
    ["frosttalon","Frosttalon Eagle","a silver eagle with blue crystal talons and wide ice-tipped wings","Talon Flurry","Summit Squall","swift","rare","#91c9e8"],
    ["quartzback","Quartzback Armadillo","a round lavender armadillo with a chunky quartz crystal shell and small pink snout","Quartz Roll","Crystal Fort","guard","uncommon","#b6a3d7"],
    ["cobaltrook","Cobalt Rook","a giant cobalt raven with silver armor feathers, black beak and bright cyan eyes","Cobalt Peck","Steelwing Storm","pierce","epic","#678fdb"],
    ["gravelmole","Gravelpaw Mole","a brown burrowing mole with stone digging claws and a golden miner helmet","Gravel Toss","Tunnel Rumble","splash","common","#ba935e"],
    ["summitogre","Summitclub Ogre","a blue mountain ogre in a shaggy white fur vest holding a rounded stone club","Stone Club","Peakbreaker","balanced","rare","#83abc8"],
    ["avalancheape","Avalanche Ape","a hulking white mountain ape with ice-blue hands and a crown of stone ridges","Snow Slam","Avalanche Roar","splash","legendary","#bad9ed"],
    ["shardhorn","Shardhorn Ibex","a black ibex with turquoise shard horns and silver geometric hoof armor","Shard Jolt","Prism Stampede","reflect","uncommon","#73c5c5"],
    ["granitegryphon","Granitewing Gryphon","a winged gryphon with granite-gray lion body and amber crystal eagle head","Granite Claw","Skyrock Barrage","charge","epic","#bfa27d"],
    ["ironpeak","Ironpeak Titan","a towering silver mountain titan with angular iron armor and glowing ruby core","Iron Fist","Mountainfall","guard","mythical","#b5bec7"],
    ["coralcolossus","Coralcrest Colossus","a broad coral-pink reef golem with blue anemone hands and branching coral crown","Coral Punch","Reefquake","guard","legendary","#e991a8"],
    ["pearlwitch","Pearlmoon Witch","a lilac merfolk witch with a pearl crown, coiled fish tail and silver shell wand","Pearl Bolt","Moonlit Tide","pierce","rare","#c2a4df"],
    ["tidalorca","Tidalcrest Orca","a hovering black and white orca with turquoise wave fins and a bright blue crest","Wave Bump","Tidal Parade","splash","epic","#72bdcf"],
    ["reefjaw","Reefjaw Shark","a small blue reef shark with orange coral dorsal fin and broad friendly jaws","Reef Snap","Shark Surge","swift","common","#71acdf"],
    ["barnacleking","Barnacle King","a stout purple crab wearing a blue barnacle crown with oversized armored claws","Barnacle Clack","Royal Shellwall","guard","uncommon","#a38bd5"],
    ["jellylantern","Jellylantern Seer","a golden jellyfish with a blue glowing bell and seven trailing amber tentacles","Lantern Sting","Sea of Lights","weaken","rare","#e4c56a"],
    ["kelpkraken","Kelpveil Kraken","a huge teal octopus with a crown of emerald kelp and eight curled powerful arms","Kelp Lash","Emerald Whirlpool","splash","legendary","#61b5a2"],
    ["seaglassdrake","Seaglass Drake","a slender aquamarine water dragon with translucent glass fins and pearl horns","Glass Spray","Ocean Prism","reflect","epic","#81d5d9"],
    ["shelloracle","Spiralshell Oracle","a violet sea snail sage with golden spiral shell and a little silver staff","Shell Chime","Spiral Blessing","regenerate","uncommon","#be97dc"],
    ["abyssangler","Abysslight Angler","a midnight-blue armored anglerfish with a radiant star lure and purple fan fins","Abyss Flash","Deepstar Nova","pierce","mythical","#848ae8"],
    ["dunejackal","Duneboot Jackal","a sandy jackal scout with blue scarf and a curved bronze dagger","Dune Dash","Sandtrack Rush","swift","common","#d4b07b"],
    ["mirageserpent","Miragecoil Serpent","an orange and turquoise cobra with shimmering diamond hood markings","Mirage Spit","Desert Dream","weaken","epic","#daa65e"],
    ["ambercobra","Amberfang Cobra","a coiled honey-gold cobra with amber crystal fangs and a small red crown","Amber Strike","Golden Coil","balanced","uncommon","#e1b850"],
    ["glassscorpion","Glassclaw Scorpion","a purple desert scorpion with transparent cyan pincers and arched crystal tail","Glass Sting","Shardstorm","reflect","rare","#b5a1dd"],
    ["sunscarab","Sunplate Scarab","a golden scarab beetle with red solar disc shell and six stout armored legs","Sun Roll","Solar Bulwark","guard","uncommon","#e6b15b"],
    ["oasisdjinn","Oasiswell Djinn","a mint-blue genie with a golden turban, water-droplet torso and curling whirlpool tail","Oasis Spark","Wishing Wave","regenerate","legendary","#7fd6cf"],
    ["sandstonegiant","Sandstone Mason","a squat orange sandstone giant with turquoise mosaic fists and square head","Sandblock Toss","Pyramid Rumble","splash","rare","#d9a366"],
    ["brassvulture","Brasswing Vulture","a bronze mechanical desert vulture with silver beak and jewel-green wing tips","Brass Peck","Sunward Dive","charge","common","#bc925c"],
    ["dustdancer","Dustveil Dancer","a swirling crimson sand spirit with gold mask, ribbon arms and a tornado lower body","Dust Flick","Sirocco Waltz","swift","epic","#db927b"],
    ["pharaohcat","Pharaohstar Cat","a regal black feline sphinx with striped blue-gold headdress and celestial anklets","Royal Claw","Starlit Dynasty","pierce","mythical","#9ab2e9"],
    ["ashminotaur","Ashhorn Minotaur","a charcoal bull warrior with orange volcanic horns and a broad brass hammer","Ash Hammer","Caldera Stampede","balanced","legendary","#d59b6c"],
    ["lavacrab","Lavashell Crab","a small ruby-red crab with black rock shell and bright orange claw tips","Lava Clack","Molten Splash","splash","common","#dc785e"],
    ["emberwasp","Emberwing Wasp","a black and gold wasp with fiery orange wings and ruby abdomen","Ember Dart","Spark Swarm","swift","uncommon","#d6ad64"],
    ["sootimp","Sootcap Imp","a squat purple imp with a sooty orange cap and a little glowing coal staff","Soot Puff","Smoky Trick","weaken","common","#ab83bb"],
    ["magmawyrm","Magmafin Wyrm","a chunky orange lava serpent with black plated back and ruby crystal fins","Magma Breath","Lavaflow","splash","epic","#e99066"],
    ["furnaceknight","Furnaceplate Knight","a heavy bronze armored knight with a fiery furnace chest and iron tower shield","Furnace Bash","Ironfire Wall","guard","rare","#cf9b65"],
    ["cinderphoenix","Cinderplume Phoenix","a crimson phoenix with gold flame feathers and a curling violet ember tail","Cinder Feather","Phoenix Renewal","regenerate","legendary","#ec956d"],
    ["basaltbull","Basaltback Bull","a black basalt bull with broad silver horns and glowing orange hooves","Basalt Bump","Bedrock Rush","reflect","uncommon","#a9967b"],
    ["coalwitch","Coalglow Witch","a small russet fox witch in black robes with an orange coal orb floating above one paw","Coal Hex","Embermoon","charge","rare","#c08b83"],
    ["infernohound","Infernostar Hound","a towering three-headed violet fire hound with gold collars and contained orange flame mane","Triple Flame","Inferno Chorus","pierce","mythical","#ca8cae"],
    ["icetooth","Icetooth Walrus","a blue-gray walrus with thick ivory tusks, white mustache and ice crystal back","Tusk Bump","Glacier Roll","balanced","common","#9fbddc"],
    ["snowharpy","Snowfeather Harpy","a white owl harpy with lavender face, blue scarf and wide feathered arm wings","Snowfeather Slash","Winter Wingbeat","swift","rare","#b6b2e2"],
    ["rimegolem","Rimeblock Golem","a squat mint-blue ice block golem with ruby eyes and square snow-capped fists","Rime Fist","Icewall","guard","uncommon","#90d1d7"],
    ["wintermoth","Winterveil Moth","a large silver moth with blue snowflake wing patterns and a fuzzy lavender body","Frost Dust","Midwinter Veil","weaken","epic","#aaaee0"],
    ["hoarfrostbear","Hoarfrost Bear","a sturdy white polar bear with blue crystal claws and a crown of frozen branches","Frost Paw","Snowfield Roar","splash","rare","#afd7e8"],
    ["glacialturtle","Glacialback Turtle","a pale cyan turtle with a faceted purple iceberg shell and golden eyes","Glacial Bump","Frozen Fortress","reflect","uncommon","#9fcbe8"],
    ["frostcrown","Frostcrown Regent","a regal ice spirit with blue crystal crown, white robes and a curling snowy ghost tail","Royal Frost","Crystal Coronation","pierce","legendary","#9dd6ed"],
    ["blizzardelk","Blizzardhoof Elk","a lavender elk with snowflake antlers and a white windblown mane","Snow Kick","Blizzard Gallop","charge","epic","#c0b4e8"],
    ["aurorawyrm","Aurorascale Wyrm","a long teal dragon with pink aurora ribbon wings and pearl horn crest","Aurora Beam","Polar Dawn","regenerate","mythical","#83d6ce"],
    ["crystalpenguin","Crystalcap Penguin","a stout navy penguin wearing a blue crystal helmet and carrying an icy paddle","Ice Paddle","Snowcap Shuffle","balanced","common","#86b8df"],
    ["cogarachnid","Cogweb Arachnid","a brass clockwork spider with eight gear-jointed legs and glowing cyan eyes","Cog Skitter","Clockweb","swift","common","#d1ad69"],
    ["steamrhino","Steamplate Rhino","a copper robotic rhinoceros with a silver drill horn and small steam chimney","Drill Charge","Steam Stampede","balanced","rare","#c09f83"],
    ["copperjester","Coppercap Jester","a copper toy jester with green spring legs, bell hat and rounded baton","Spring Bonk","Clockwork Carnival","weaken","uncommon","#c8ac6a"],
    ["clockmantis","Clockblade Mantis","a silver mechanical mantis with blue clock-face chest and gold blade arms","Clock Slash","Minute Flurry","swift","epic","#a9bbc8"],
    ["mercurygargoyle","Mercurywing Gargoyle","a glossy silver gargoyle with folded violet crystal wings and three blue eyes","Mercury Glint","Mirrorwing","reflect","legendary","#b7b2d9"],
    ["gearbehemoth","Gearjaw Behemoth","a huge bronze robot gorilla with gear shoulders, cyan furnace heart and massive fists","Gear Smash","Assembly Quake","guard","epic","#cfab71"],
    ["voltvulture","Voltwing Vulture","a teal electric robot vulture with golden lightning wing feathers and yellow beak","Volt Dart","Thunder Circuit","charge","rare","#7cbac3"],
    ["magnetmaw","Magnetmaw Mimic","a red metal horseshoe magnet creature with little iron feet and an open square jaw","Magnet Pull","Polarity Pulse","splash","uncommon","#d98784"],
    ["prismdroid","Prismcore Droid","a floating white diamond robot with four small crystal fins and rainbow central lens","Prism Bolt","Spectrum Beam","pierce","common","#a9cbe1"],
    ["chronotitan","Chronocrown Titan","a towering gold clockwork titan with a blue hourglass chest, silver limbs and crown gears","Time Hammer","Hourglass Nova","guard","mythical","#d7bd79"],
    ["lunarcobra","Lunarcrown Cobra","a silver lunar cobra with a crescent-shaped lavender hood and midnight star scales","Lunar Fang","Mooncoil","weaken","rare","#b2a3df"],
    ["sunlion","Sunmane Lion","a golden lion with a red solar-disc mane and brilliant amber paws","Sun Claw","Dawn Roar","balanced","legendary","#e8bd64"],
    ["starmantis","Starlance Mantis","a midnight-blue mantis with silver star-speckled shell and cyan spear-like forearms","Star Lance","Meteor Flurry","swift","uncommon","#8ca9df"],
    ["voidmanta","Voidveil Manta","a floating deep-purple manta ray with turquoise luminous fins and a white crescent forehead","Void Ripple","Nightfall Wave","splash","epic","#9b90d4"],
    ["cometgryphon","Cometwing Gryphon","a violet gryphon with golden comet eagle wings and a long blue starlight tail","Comet Claw","Starfall Dive","charge","legendary","#b39ada"],
    ["eclipseknight","Eclipseplate Knight","a black and silver armored knight with a crescent shield and a violet glowing sword","Eclipse Slash","Moonshield","guard","epic","#a69ac9"],
    ["nebulajelly","Nebulabell Jelly","a floating pink cosmic jellyfish with blue star-marked bell and six lavender tendrils","Nebula Spark","Cloud of Stars","regenerate","rare","#c7a4df"],
    ["orbitgolem","Orbitstone Golem","a squat navy stone golem with three small gold rings around its shoulders and glowing green eyes","Orbit Punch","Planetwall","reflect","uncommon","#98b4c6"],
    ["constellastag","Constellacrown Stag","a luminous ivory stag with blue star-branch antlers and violet crystal hooves","Starhoof","Constellation Dance","pierce","mythical","#b1c9ed"],
    ["cosmicwyrm","Cosmicscale Wyrm","a curled sapphire dragon with gold orbit-ring fins and a bright magenta galaxy core","Cosmic Breath","Galaxy Bloom","splash","mythical","#a29be3"],
    ["bookwyrm","Bookspine Wyrm","a small green dragon made of layered red and gold books with page-shaped wings","Page Flick","Library Cyclone","weaken","rare","#a4bc78"],
    ["candyking","Candystone King","a stout candy crystal golem with pink peppermint crown and blue sugar fists","Sugar Smash","Sweetstone Wall","guard","epic","#df9fc8"],
    ["mirrorwitch","Mirrorveil Witch","an ivory porcelain witch with silver mirror face, violet robes and a crystal wand","Mirror Bolt","Silver Reflection","reflect","legendary","#b6a5db"],
    ["dreamchimera","Dreamweave Chimera","a majestic lavender lion with teal dragon wings, a white owl head and a golden serpent tail","Dream Claw","Dreamstar Symphony","pierce","mythical","#b2a0de"]
  ].map(function(d,index) {
    var rank={common:0,uncommon:1,rare:2,epic:3,legendary:4,mythical:5}[d[6]];
    var strategies={balanced:'Steady focused attacks and a party-wide ultimate.',guard:'Raises a shield after attacking. Use strong skills to break through.',reflect:'Counters successful attacks. Keep your party healthy.',swift:'Strikes twice on normal turns. Shields soften the flurry.',weaken:'Weakens the next hero attack. Cleanse helps restore strength.',regenerate:'Recovers a little health after normal attacks. Coordinate burst damage.',splash:'Normal attacks reach the whole party. Bring healing and protective wards.',pierce:'Magic partially bypasses defence. Healing keeps allies standing.',charge:'Charges its ultimate quickly. Time your defensive skills carefully.'};
    var sheet='assets/battle-pixel/bosses/atlas-'+String(Math.floor(index/10)+1).padStart(2,'0')+'.png';
    return {id:d[0],name:d[1],subject:d[2],attackName:d[3],ultimateName:d[4],playstyle:d[5],rarity:d[6],color:d[7],
      tier:['Skirmish','Skirmish','Elite','Elite','Boss','Mythic boss'][rank],description:strategies[d[5]],
      hpMultiplier:Number(([.5,.7,.95,1.25,1.8,2.45][rank]+(index%3)*.08).toFixed(2)),
      attackMultiplier:Number(([.45,.6,.8,1,1.2,1.45][rank]*(d[5]==='swift'?.8:1)).toFixed(2)),
      defence:Number(Math.min(.28,[0,.04,.07,.1,.14,.2][rank]+(d[5]==='guard'?.07:0)).toFixed(2)),
      chargeMax:d[5]==='charge'?2:(rank<2?4:3),rewardXp:[45,65,85,115,165,225][rank],legacy:false,image:sheet,
      art:{sheet:sheet,col:index%5,row:Math.floor((index%10)/5),columns:5,rows:2,aspect:1983*2/(793*5)}};
  })).map(function(b) {
    if(b.legacy || b.rarity) return b;
    return Object.assign({},b,{rarity:{goblin:'common',slime:'common','goblin-shaman':'rare',golem:'epic',dragon:'legendary',lich:'mythical'}[b.id]});
  }); });
